name: surepay_pos_plugin
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/abdalmuneim/sure_pos_plugin

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.mnemdev.surepay_pos_plugin
        pluginClass: SurepayPosPlugin
      ios:
        pluginClass: SurepayPosPlugin
      linux:
        pluginClass: SurepayPosPlugin
      macos:
        pluginClass: SurepayPosPlugin
      windows:
        pluginClass: SurepayPosPluginCApi

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
